### ISSUE TITLE
Update CONTRIBUTING.md file

### ISSUE THREAD

**Issue by adviksinghania** [adviksinghania/ethical-hacking-scripts#1]
Write a nice CONTRIBUTING.md markdown file with steps on how to contribute the Python scripts to this repository. Also include the code of conduct for Hacktoberfest 2022

**Comment by Rituraj-13** [comment]
Hey, I want to work on this. Can you please assign this to me?

**Comment by adviksinghania** [comment]
Sure @Rituraj-13 , you can update the file, adding a code of conduct, removing the unresolved image and any other modifications you may find.
